[package]

name = "glium_image"
version = "0.0.1"
authors = ["Pierre Krieger <pierre.krieger1708@gmail.com>"]

[dependencies.glium_core]
path = "../core"

[dependencies.image]
git = "https://github.com/PistonDevelopers/rust-image"

[dev-dependencies.glium_sprite2d]
path = "../sprite2d"
