[package]

name = "glium_filter"
version = "0.0.1"
authors = ["Pierre Krieger <pierre.krieger1708@gmail.com>"]

[dependencies.glium_core]
path = "../core"

[dev-dependencies.glium_image]
path = "../image"

[dev-dependencies.glium_sprite2d]
path = "../sprite2d"
